sudo: false
language: ruby
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: head
script: bundle exec rake
before_install:
  - gem update --system
  - gem install bundler
services:
  - redis-server
